[RefSi] Restore CMAKE_C(XX)_EXTENSIONS.
We cannot expect external projects to account for our changes from CMake
defaults.

Fixes:

/builds/ComputeAorta/ci-github/oneapi-construction-kit/build/_deps/riscv-isa-sim-src/fdt/fdt_ro.c: In function ‘fdt_stringlist_count’:
/builds/ComputeAorta/ci-github/oneapi-construction-kit/build/_deps/riscv-isa-sim-src/fdt/fdt_ro.c:711:12: warning: implicit declaration of function ‘strnlen’; did you mean ‘strlen’? [-Wimplicit-function-declaration]
  711 |   length = strnlen(list, end - list) + 1;
      |            ^~~~~~~
      |            strlen