[spirv-ll] Print human-readable capability names in errors
Previously we'd print something like:

    error: OpCapability 57 not supported by device

.. and every time, someone would have to look up what that means in the
code.

This adds human-readable capability names to such error messages, making
development easier and any bug reports immediately more understandable.

Now users should see something lke:

    error: OpCapability MultiViewport (#57) not supported by device

It does involve a hard-coded list of capabilities we understand, because
we pull in the official headers and they don't provide this for us. But
that's still better, in my opinion, than printing out obscure integers;
we don't bump the headers that often.