Add missing reference for threads.
After the bump to OpenCL ICD Loader, on Ubuntu 20, linking FuzzCL fails
with an undefined reference to pthread_create. It appears that the older
version of OpenCL ICD Loader implicitly referenced libpthread, whereas
the newer version does not. Explicitly add the reference instead.